<?task5_1 version="1.0" encoding="UTF-8"?>
<!DOCTYPE Candy [
        <!ELEMENT Candy (Name|Energy|Type|Ingredients|Value|Production)*>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Energy (#PCDATA)>
        <!ELEMENT Type (CandyType)*>
        <!ELEMENT CandyType (#PCDATA)>
        <!ELEMENT Ingredients (Water|Sugar|Fructose|Vanillin)*>
        <!ELEMENT Water (#PCDATA)>
        <!ELEMENT Sugar (#PCDATA)>
        <!ELEMENT Fructose (#PCDATA)>
        <!ELEMENT Vanillin (#PCDATA)>
        <!ELEMENT Value (Protein|Fat|Carbohydrate)*>
        <!ELEMENT Protein (#PCDATA)>
        <!ELEMENT Fat (#PCDATA)>
        <!ELEMENT Carbohydrate (#PCDATA)>
        <!ELEMENT Production (#PCDATA)>
        ]>
<Candy>
    <Name>Чупа-чупс</Name>
    <Energy>50</Energy>
    <Type>
        <CandyType>Карамель</CandyType>
    </Type>
    <Ingredients>
        <Water>100</Water>
        <Sugar>200</Sugar>
        <Fructose>50</Fructose>
        <Vanillin>1</Vanillin>
    </Ingredients>
    <Value>
        <Protein>0</Protein>
        <Fat>0</Fat>
        <Carbohydrate>75</Carbohydrate>
    </Value>
    <Production>Сяйво</Production>
    <Name>Чайка</Name>
    <Energy>500</Energy>
    <Type>
        <CandyType>Шоколадна</CandyType>
    </Type>
    <Ingredients>
        <Water>10</Water>
        <Sugar>150</Sugar>
        <Fructose>0</Fructose>
        <Vanillin>12</Vanillin>
    </Ingredients>
    <Value>
        <Protein>10</Protein>
        <Fat>25</Fat>
        <Carbohydrate>10</Carbohydrate>
    </Value>
    <Production>Арія</Production>
    <Name>Желейна</Name>
    <Energy>100</Energy>
    <Type>
        <CandyType>Фруктова</CandyType>
    </Type>
    <Ingredients>
        <Water>50</Water>
        <Sugar>100</Sugar>
        <Fructose>50</Fructose>
        <Vanillin>1</Vanillin>
    </Ingredients>
    <Value>
        <Protein>5</Protein>
        <Fat>0</Fat>
        <Carbohydrate>65</Carbohydrate>
    </Value>
    <Production>Срібло</Production>
</Candy>
